// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import {ERC4626} from "@openzeppelin/contracts/token/ERC20/extensions/ERC4626.sol";
import {ERC20} from "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {IERC20Metadata} from "@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata.sol";
import {SafeERC20} from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";
import {Pausable} from "@openzeppelin/contracts/utils/Pausable.sol";
import {ReentrancyGuard} from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import {Math} from "@openzeppelin/contracts/utils/math/Math.sol";

/// @notice Circle CCTP TokenMessenger — burn USDC on source, mint native USDC on destination.
///         Only the depositForBurn entry point is needed here; on destination, Circle's
///         MessageTransmitter mints USDC directly to the registered mintRecipient (Relayer).
interface ITokenMessenger {
    function depositForBurn(uint256 amount, uint32 destinationDomain, bytes32 mintRecipient, address burnToken)
        external
        returns (uint64 nonce);
}

/// @title MirrorVault
/// @notice ERC-4626 vault deployed on Base. Users deposit once; the vault
///         distributes LP positions across Base, Ethereum, (and BNB once enabled)
///         through CCTP bridging + MirrorHook + Relayer contracts. Earns a 15%
///         performance fee on the EXTRA yield generated by cross-chain mirroring
///         vs. single-chain baseline.
///
/// @dev Three feature surfaces:
///      1. ERC-4626 deposits/redeems with a chain allocation registry — deposit
///         USDC is split per `chainConfigs` allocations and CCTP-bridged to sister
///         Relayers automatically.
///      2. Async withdrawal queue — when local USDC isn't enough to cover a
///         redemption, the request is queued, sister LP is unwound off-chain
///         by the CoordinatorAgent, USDC bridges back via CCTP, fulfillment
///         pays out.
///      3. Multi-chain extensibility — adding/removing chains is an admin tx,
///         no vault redeploy required.
///
/// @dev Immutable contract — no proxy. Performance fee:
///        extraYield = totalAssetsNow - principalTracked - baselineYieldAccrued
///        fee        = extraYield * PERFORMANCE_FEE_BPS / 10_000
///      Fee is paid by minting new vault shares to the treasury.
///
/// @dev totalAssets() = localUsdcBalance + crossChainAssetsReported.
///      Cross-chain assets include both deployed LP value and CCTP-in-flight
///      bridge legs — both reported by CoordinatorAgent via updateCrossChainAssets().
contract MirrorVault is ERC4626, Ownable, Pausable, ReentrancyGuard {
    using SafeERC20 for IERC20;
    using Math for uint256;

    // ─── Errors ─────────────────────────────────────────────────────────────
    error NotAuthorizedAgent();
    error ZeroAddress();
    error ZeroAmount();
    error NoExtraYield();
    error HarvestTooSoon();
    error ExceedsMaxMove();
    error ChainAlreadyEnabled();
    error ChainNotEnabled();
    error ChainHasInFlightFunds();
    error AllocationsMustSum10000();
    error InsufficientLocalBalance();
    error WithdrawAlreadyFulfilled();
    error WithdrawAlreadyCancelled();
    error InvalidWithdrawRequest();
    error TooEarlyToCancel();
    error NotRequester();
    error InvalidArrayLengths();

    // ─── Events ─────────────────────────────────────────────────────────────
    event PerformanceFeePaid(uint256 extraYield, uint256 feeShares, address indexed treasury);
    event CrossChainAssetsUpdated(uint256 newValue);
    event BaselineApyUpdated(uint256 newApyBps);
    event AgentAuthorizationUpdated(address indexed agent, bool authorized);
    event TreasuryUpdated(address indexed oldTreasury, address indexed newTreasury);
    event RebalanceExecuted(address indexed agent, uint256 amount0, uint256 amount1);
    event PrincipalSnapshotTaken(uint256 principal, uint256 timestamp);
    event ChainAdded(uint32 indexed hyperlaneDomain, uint16 allocationBps);
    event ChainRemoved(uint32 indexed hyperlaneDomain);
    event AllocationsUpdated(uint32[] domains, uint16[] bps);
    event CctpBridgeSent(uint32 indexed cctpDomain, bytes32 indexed recipient, uint256 amount, uint64 nonce);
    event WithdrawRequested(
        uint256 indexed requestId, address indexed requester, address receiver, uint256 shares, uint256 expectedAssets
    );
    event WithdrawFulfilled(uint256 indexed requestId, address indexed receiver, uint256 assetsPaid);
    event WithdrawCancelled(uint256 indexed requestId);

    // ─── Constants ───────────────────────────────────────────────────────────
    uint256 public constant PERFORMANCE_FEE_BPS = 1500; // 15%
    uint256 public constant MAX_BPS = 10_000;
    uint256 public constant MIN_HARVEST_INTERVAL = 1 days;
    uint256 public constant WITHDRAW_CANCEL_DELAY = 24 hours;

    // ─── Types ───────────────────────────────────────────────────────────────
    /// @dev Per-chain bridge configuration. Allocations across all enabled
    ///      chains MUST sum to 10_000 BPS. CCTP fields are required for USDC
    ///      bridging on USDC-supporting chains; warpRouter is reserved for
    ///      future WETH bridging (not used in v4 since Relayer holds WETH inventory).
    struct ChainConfig {
        uint32 cctpDomain;       // Circle CCTP domain ID (0 if N/A — disables USDC bridging)
        bytes32 cctpRecipient;   // bytes32(uint160(sisterRelayer)) — CCTP mint recipient
        address warpRouter;      // Hyperlane warp router on Base (future: for non-USDC)
        bytes32 warpRecipient;   // bytes32(uint160(sisterRelayer))
        uint16 allocationBps;    // 0–10000
        bool enabled;
    }

    struct WithdrawRequest {
        address requester;
        address receiver;
        uint256 shares;
        uint256 expectedAssets; // snapshot at request time for UX display
        uint256 createdAt;
        bool fulfilled;
        bool cancelled;
    }

    // ─── State ───────────────────────────────────────────────────────────────
    /// @notice Treasury contract that receives performance fees
    address public treasury;

    /// @notice Circle CCTP TokenMessenger on Base — used to burn USDC for cross-chain mint
    ITokenMessenger public immutable cctpMessenger;

    /// @notice AI agent addresses authorized to call privileged functions
    mapping(address => bool) public authorizedAgents;

    /// @notice USD-equivalent value of LP positions held cross-chain plus
    ///         in-flight CCTP bridge legs (asset decimals — for USDC vault: 1e6).
    ///         Updated by CoordinatorAgent each cycle via updateCrossChainAssets.
    uint256 public crossChainAssetsReported;

    /// @notice Baseline single-chain APY in BPS (e.g. 800 = 8%).
    uint256 public baselineApyBps;

    /// @notice Total principal tracked (deposits - withdrawals) in asset decimals
    uint256 public principalTracked;

    /// @notice Timestamp of the last harvest
    uint256 public lastHarvestAt;

    /// @notice Cumulative baseline yield accrued since deployment (asset decimals)
    uint256 public baselineYieldAccrued;

    /// @notice Snapshot timestamp used for baseline yield accrual
    uint256 public lastBaselineSnapshotAt;

    // ─── Chain registry ──────────────────────────────────────────────────────
    /// @notice Per-Hyperlane-domain bridge configuration
    mapping(uint32 => ChainConfig) public chainConfigs;
    /// @notice Enabled domains for iteration (deposit splitting)
    uint32[] public enabledDomains;

    // ─── Withdrawal queue ────────────────────────────────────────────────────
    mapping(uint256 => WithdrawRequest) public withdrawRequests;
    uint256 public nextRequestId;

    // ─── Constructor ─────────────────────────────────────────────────────────
    /// @param _asset           Underlying token (USDC on Base)
    /// @param _cctpMessenger   Circle CCTP TokenMessenger on Base
    /// @param _treasury        Treasury contract address
    /// @param _owner           Owner (multisig recommended)
    /// @param _name            Vault share token name
    /// @param _symbol          Vault share token symbol
    constructor(
        IERC20 _asset,
        address _cctpMessenger,
        address _treasury,
        address _owner,
        string memory _name,
        string memory _symbol
    ) ERC4626(_asset) ERC20(_name, _symbol) Ownable(_owner) {
        if (_treasury == address(0) || _cctpMessenger == address(0)) revert ZeroAddress();
        treasury = _treasury;
        cctpMessenger = ITokenMessenger(_cctpMessenger);
        lastHarvestAt = block.timestamp;
        lastBaselineSnapshotAt = block.timestamp;
    }

    // ─── ERC-4626 overrides ───────────────────────────────────────────────────

    /// @notice Total assets = local USDC balance + cross-chain LP value + in-flight bridges
    function totalAssets() public view override returns (uint256) {
        return IERC20(asset()).balanceOf(address(this)) + crossChainAssetsReported;
    }

    /// @dev Deposit: pulls USDC, mints shares, then bridges per-chain allocations
    ///      to sister Relayers via CCTP. The portion allocated to Base (the local
    ///      domain) stays in the vault for the Base hook's LP path.
    function _deposit(address caller, address receiver, uint256 assets, uint256 shares)
        internal
        override
        whenNotPaused
    {
        super._deposit(caller, receiver, assets, shares);
        principalTracked += assets;
        _accrueBaseline();
        _splitAndBridge(assets);
    }

    /// @dev Standard ERC-4626 withdraw — must have enough local USDC. Reverts if not;
    ///      callers should use `requestWithdraw` for the async cross-chain unwind path.
    function _withdraw(address caller, address receiver, address owner_, uint256 assets, uint256 shares)
        internal
        override
        whenNotPaused
    {
        if (IERC20(asset()).balanceOf(address(this)) < assets) revert InsufficientLocalBalance();
        super._withdraw(caller, receiver, owner_, assets, shares);
        if (assets > principalTracked) {
            principalTracked = 0;
        } else {
            principalTracked -= assets;
        }
        _accrueBaseline();
    }

    // ─── Performance fee harvesting ───────────────────────────────────────────

    /// @notice Harvest accumulated performance fees. Callable by authorized agents.
    function harvest() external nonReentrant {
        if (!authorizedAgents[msg.sender]) revert NotAuthorizedAgent();
        if (block.timestamp - lastHarvestAt < MIN_HARVEST_INTERVAL) revert HarvestTooSoon();

        _accrueBaseline();

        uint256 total = totalAssets();
        if (total <= principalTracked + baselineYieldAccrued) revert NoExtraYield();

        uint256 extraYield = total - principalTracked - baselineYieldAccrued;
        uint256 feeAssets = extraYield.mulDiv(PERFORMANCE_FEE_BPS, MAX_BPS, Math.Rounding.Floor);

        if (feeAssets == 0) revert NoExtraYield();

        uint256 feeShares = previewDeposit(feeAssets);
        _mint(treasury, feeShares);

        principalTracked += feeAssets;
        lastHarvestAt = block.timestamp;

        emit PerformanceFeePaid(extraYield, feeShares, treasury);
    }

    // ─── Agent-callable ──────────────────────────────────────────────────────

    function updateCrossChainAssets(uint256 newValue) external {
        if (!authorizedAgents[msg.sender]) revert NotAuthorizedAgent();
        crossChainAssetsReported = newValue;
        emit CrossChainAssetsUpdated(newValue);
    }

    function updateBaselineApy(uint256 newApyBps) external {
        if (!authorizedAgents[msg.sender]) revert NotAuthorizedAgent();
        if (newApyBps > MAX_BPS) revert ZeroAmount();
        _accrueBaseline();
        baselineApyBps = newApyBps;
        emit BaselineApyUpdated(newApyBps);
    }

    function recordRebalance(uint256 amount0, uint256 amount1) external {
        if (!authorizedAgents[msg.sender]) revert NotAuthorizedAgent();
        emit RebalanceExecuted(msg.sender, amount0, amount1);
    }

    // ─── Async withdrawal queue ──────────────────────────────────────────────

    /// @notice Queue a withdrawal that requires cross-chain unwind. Shares are
    ///         held in vault custody (not yet burned) so totalSupply stays
    ///         consistent until fulfillment. Cancellable after WITHDRAW_CANCEL_DELAY
    ///         if the agent fails to fulfill (escalation path).
    function requestWithdraw(uint256 shares, address receiver) external whenNotPaused returns (uint256 requestId) {
        if (shares == 0) revert ZeroAmount();
        if (receiver == address(0)) revert ZeroAddress();

        // Hold caller's shares in vault custody (transfer, don't burn — keeps share price stable)
        _transfer(msg.sender, address(this), shares);

        uint256 expectedAssets = convertToAssets(shares);
        requestId = nextRequestId++;
        withdrawRequests[requestId] = WithdrawRequest({
            requester: msg.sender,
            receiver: receiver,
            shares: shares,
            expectedAssets: expectedAssets,
            createdAt: block.timestamp,
            fulfilled: false,
            cancelled: false
        });

        emit WithdrawRequested(requestId, msg.sender, receiver, shares, expectedAssets);
    }

    /// @notice Agent fulfills a queued withdrawal once enough USDC is back on Base.
    ///         Computes payout at CURRENT share price (not the request-time snapshot)
    ///         so the requester gets the value of their shares at fulfillment time.
    function fulfillWithdraw(uint256 requestId) external nonReentrant whenNotPaused {
        if (!authorizedAgents[msg.sender]) revert NotAuthorizedAgent();
        WithdrawRequest storage req = withdrawRequests[requestId];
        if (req.shares == 0) revert InvalidWithdrawRequest();
        if (req.fulfilled) revert WithdrawAlreadyFulfilled();
        if (req.cancelled) revert WithdrawAlreadyCancelled();

        uint256 assetsOwed = convertToAssets(req.shares);
        if (IERC20(asset()).balanceOf(address(this)) < assetsOwed) revert InsufficientLocalBalance();

        // Burn the custodial shares
        _burn(address(this), req.shares);

        // Pay out
        IERC20(asset()).safeTransfer(req.receiver, assetsOwed);

        if (assetsOwed > principalTracked) {
            principalTracked = 0;
        } else {
            principalTracked -= assetsOwed;
        }
        _accrueBaseline();

        req.fulfilled = true;
        emit WithdrawFulfilled(requestId, req.receiver, assetsOwed);
    }

    /// @notice Requester escalation path: if a request sits unfulfilled longer
    ///         than WITHDRAW_CANCEL_DELAY (24h), the requester can reclaim shares.
    function cancelWithdraw(uint256 requestId) external {
        WithdrawRequest storage req = withdrawRequests[requestId];
        if (msg.sender != req.requester) revert NotRequester();
        if (req.fulfilled) revert WithdrawAlreadyFulfilled();
        if (req.cancelled) revert WithdrawAlreadyCancelled();
        if (block.timestamp < req.createdAt + WITHDRAW_CANCEL_DELAY) revert TooEarlyToCancel();

        // Return shares to requester
        _transfer(address(this), req.requester, req.shares);
        req.cancelled = true;

        emit WithdrawCancelled(requestId);
    }

    // ─── Chain registry admin ────────────────────────────────────────────────

    /// @notice Add a new sister chain. Allocations across all enabled chains
    ///         must sum to 10000 after the change — caller should follow up
    ///         with setAllocations to rebalance if needed.
    function addChain(
        uint32 hyperlaneDomain,
        uint32 cctpDomain,
        bytes32 cctpRecipient,
        address warpRouter,
        bytes32 warpRecipient,
        uint16 allocationBps
    ) external onlyOwner {
        if (chainConfigs[hyperlaneDomain].enabled) revert ChainAlreadyEnabled();

        chainConfigs[hyperlaneDomain] = ChainConfig({
            cctpDomain: cctpDomain,
            cctpRecipient: cctpRecipient,
            warpRouter: warpRouter,
            warpRecipient: warpRecipient,
            allocationBps: allocationBps,
            enabled: true
        });
        enabledDomains.push(hyperlaneDomain);

        emit ChainAdded(hyperlaneDomain, allocationBps);
    }

    /// @notice Remove a sister chain. Allocation must be 0 (caller should have
    ///         rebalanced via setAllocations beforehand) AND the chain must
    ///         have no in-flight USDC pending (off-chain check, can't enforce
    ///         on-chain without a per-chain in-flight accumulator).
    function removeChain(uint32 hyperlaneDomain) external onlyOwner {
        if (!chainConfigs[hyperlaneDomain].enabled) revert ChainNotEnabled();
        if (chainConfigs[hyperlaneDomain].allocationBps != 0) revert ChainHasInFlightFunds();

        chainConfigs[hyperlaneDomain].enabled = false;

        // remove from enabledDomains array (swap-and-pop)
        uint256 len = enabledDomains.length;
        for (uint256 i; i < len; ++i) {
            if (enabledDomains[i] == hyperlaneDomain) {
                enabledDomains[i] = enabledDomains[len - 1];
                enabledDomains.pop();
                break;
            }
        }

        emit ChainRemoved(hyperlaneDomain);
    }

    /// @notice Atomically set allocations across N chains; the sum must be
    ///         exactly 10000 across all enabled chains (including those not in
    ///         the input arrays — their existing allocation is preserved).
    function setAllocations(uint32[] calldata domains, uint16[] calldata bps) external onlyOwner {
        if (domains.length != bps.length) revert InvalidArrayLengths();

        for (uint256 i; i < domains.length; ++i) {
            if (!chainConfigs[domains[i]].enabled) revert ChainNotEnabled();
            chainConfigs[domains[i]].allocationBps = bps[i];
        }

        // Validate total sums to 10000 across all enabled chains
        uint256 total;
        for (uint256 i; i < enabledDomains.length; ++i) {
            total += chainConfigs[enabledDomains[i]].allocationBps;
        }
        if (total != MAX_BPS) revert AllocationsMustSum10000();

        emit AllocationsUpdated(domains, bps);
    }

    // ─── Internal: deposit splitting + bridging ──────────────────────────────

    /// @dev Splits a deposit per chain allocations and CCTP-bridges to each
    ///      sister Relayer. Chains with cctpDomain == 0 (e.g. the local Base
    ///      domain or a chain awaiting CCTP support) keep their USDC local.
    function _splitAndBridge(uint256 totalAmount) internal {
        uint256 len = enabledDomains.length;
        if (len == 0) return; // pre-launch: no chains configured yet, USDC stays local

        for (uint256 i; i < len; ++i) {
            uint32 domain = enabledDomains[i];
            ChainConfig memory cfg = chainConfigs[domain];
            uint256 alloc = (totalAmount * cfg.allocationBps) / MAX_BPS;
            if (alloc == 0) continue;
            if (cctpMessenger == ITokenMessenger(address(0))) continue;
            // cctpDomain == 0 means "stay local, don't bridge". CCTP uses 0 for Ethereum,
            // but Vault is on Base where Hyperlane domain == 8453 — Base's cctpDomain in
            // chainConfigs is set to 0 in the local-stays-local pattern (and CCTP-Ethereum
            // is wired via a different config entry). The vault's home chain doesn't
            // need a chainConfig entry at all in this model.
            if (cfg.cctpDomain == 0 && cfg.cctpRecipient == bytes32(0)) continue;

            IERC20(asset()).forceApprove(address(cctpMessenger), alloc);
            uint64 nonce =
                cctpMessenger.depositForBurn(alloc, cfg.cctpDomain, cfg.cctpRecipient, asset());

            emit CctpBridgeSent(cfg.cctpDomain, cfg.cctpRecipient, alloc, nonce);
        }
    }

    /// @dev Accrue baseline yield since last snapshot into baselineYieldAccrued
    function _accrueBaseline() internal {
        uint256 elapsed = block.timestamp - lastBaselineSnapshotAt;
        if (elapsed == 0 || principalTracked == 0 || baselineApyBps == 0) return;

        uint256 accrued = principalTracked.mulDiv(baselineApyBps * elapsed, MAX_BPS * 365 days, Math.Rounding.Floor);
        baselineYieldAccrued += accrued;
        lastBaselineSnapshotAt = block.timestamp;
    }

    // ─── Views ───────────────────────────────────────────────────────────────

    function enabledDomainsCount() external view returns (uint256) {
        return enabledDomains.length;
    }

    function getChainConfig(uint32 hyperlaneDomain) external view returns (ChainConfig memory) {
        return chainConfigs[hyperlaneDomain];
    }

    /// @notice Preview how a deposit of `assets` would split across chains.
    ///         Returns the per-chain bridged amount (in asset decimals) parallel
    ///         to `enabledDomains` ordering.
    function previewSplit(uint256 assets) external view returns (uint32[] memory domains, uint256[] memory amounts) {
        uint256 len = enabledDomains.length;
        domains = new uint32[](len);
        amounts = new uint256[](len);
        for (uint256 i; i < len; ++i) {
            domains[i] = enabledDomains[i];
            amounts[i] = (assets * chainConfigs[enabledDomains[i]].allocationBps) / MAX_BPS;
        }
    }

    // ─── Admin ───────────────────────────────────────────────────────────────

    function setTreasury(address newTreasury) external onlyOwner {
        if (newTreasury == address(0)) revert ZeroAddress();
        emit TreasuryUpdated(treasury, newTreasury);
        treasury = newTreasury;
    }

    function setAgentAuthorization(address agent, bool authorized) external onlyOwner {
        if (agent == address(0)) revert ZeroAddress();
        authorizedAgents[agent] = authorized;
        emit AgentAuthorizationUpdated(agent, authorized);
    }

    function pause() external onlyOwner {
        _pause();
    }

    function unpause() external onlyOwner {
        _unpause();
    }
}
