// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import {ERC4626} from "@openzeppelin/contracts/token/ERC20/extensions/ERC4626.sol";
import {ERC20} from "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {IERC20Metadata} from "@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata.sol";
import {SafeERC20} from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";
import {Pausable} from "@openzeppelin/contracts/utils/Pausable.sol";
import {ReentrancyGuard} from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import {Math} from "@openzeppelin/contracts/utils/math/Math.sol";

/// @title MirrorVault
/// @notice ERC-4626 vault deployed on Base. Users deposit once; the vault
///         distributes LP positions across Ethereum, Base, and BNB Chain through
///         MirrorHook + Relayer contracts. Earns a 15% performance fee on the
///         EXTRA yield generated by cross-chain mirroring vs. single-chain baseline.
///
/// @dev Immutable — no proxy. Replace by deploying a new vault and migrating.
///      Performance fee formula:
///        extraYield = totalAssetsNow - principalTracked - baselineYieldAccrued
///        fee        = extraYield * PERFORMANCE_FEE_BPS / 10_000
///        Fee is paid by minting new vault shares to the treasury.
///
/// @dev totalAssets() = localLpValue + crossChainAssetsReported
///      Cross-chain assets are reported by CoordinatorAgent via updateCrossChainAssets().
///      All amounts in asset token decimals.
contract MirrorVault is ERC4626, Ownable, Pausable, ReentrancyGuard {
    using SafeERC20 for IERC20;
    using Math for uint256;

    // ─── Errors ─────────────────────────────────────────────────────────────
    error NotAuthorizedAgent();
    error ZeroAddress();
    error ZeroAmount();
    error NoExtraYield();
    error HarvestTooSoon();
    error ExceedsMaxMove();

    // ─── Events ─────────────────────────────────────────────────────────────
    event PerformanceFeePaid(uint256 extraYield, uint256 feeShares, address treasury);
    event CrossChainAssetsUpdated(uint256 newValue);
    event BaselineApyUpdated(uint256 newApyBps);
    event AgentAuthorizationUpdated(address indexed agent, bool authorized);
    event TreasuryUpdated(address indexed oldTreasury, address indexed newTreasury);
    event RebalanceExecuted(address indexed agent, uint256 amount0, uint256 amount1);
    event PrincipalSnapshotTaken(uint256 principal, uint256 timestamp);

    // ─── Constants ───────────────────────────────────────────────────────────
    uint256 public constant PERFORMANCE_FEE_BPS = 1500;   // 15%
    uint256 public constant MAX_BPS             = 10_000;
    uint256 public constant MIN_HARVEST_INTERVAL = 1 days;

    // OpenZeppelin ERC-4626 virtual offset prevents first-depositor inflation attack
    // (already handled by OZ v5 ERC4626 _decimalsOffset default)

    // ─── State ───────────────────────────────────────────────────────────────
    /// @notice Treasury contract that receives performance fees
    address public treasury;

    /// @notice AI agent addresses authorized to call privileged functions
    mapping(address => bool) public authorizedAgents;

    /// @notice USD-equivalent value of LP positions held on Ethereum + BNB (18 decimals).
    ///         Updated by CoordinatorAgent each cycle.
    uint256 public crossChainAssetsReported;

    /// @notice Baseline single-chain APY in BPS (e.g. 800 = 8%).
    ///         Set by authorized agent based on market conditions.
    uint256 public baselineApyBps;

    /// @notice Total principal tracked (deposits - withdrawals) in asset decimals
    uint256 public principalTracked;

    /// @notice Timestamp of the last harvest
    uint256 public lastHarvestAt;

    /// @notice Cumulative baseline yield accrued since deployment (asset decimals)
    uint256 public baselineYieldAccrued;

    /// @notice Snapshot timestamp used for baseline yield accrual
    uint256 public lastBaselineSnapshotAt;

    // ─── Constructor ─────────────────────────────────────────────────────────
    /// @param _asset     Underlying token (e.g. USDC on Base)
    /// @param _treasury  Treasury contract address
    /// @param _owner     Owner (multisig)
    /// @param _name      Vault share token name (e.g. "Mirror ETH/USDC Vault")
    /// @param _symbol    Vault share token symbol (e.g. "mirvETH-USDC")
    constructor(
        IERC20 _asset,
        address _treasury,
        address _owner,
        string memory _name,
        string memory _symbol
    )
        ERC4626(_asset)
        ERC20(_name, _symbol)
        Ownable(_owner)
    {
        if (_treasury == address(0)) revert ZeroAddress();
        treasury = _treasury;
        lastHarvestAt = block.timestamp;
        lastBaselineSnapshotAt = block.timestamp;
    }

    // ─── ERC-4626 overrides ───────────────────────────────────────────────────

    /// @notice Total assets = local asset balance + cross-chain LP value reported by agents.
    ///         This is the authoritative value used for share price calculations.
    function totalAssets() public view override returns (uint256) {
        return IERC20(asset()).balanceOf(address(this)) + crossChainAssetsReported;
    }

    /// @dev Track principal on deposit
    function _deposit(address caller, address receiver, uint256 assets, uint256 shares) internal override whenNotPaused {
        super._deposit(caller, receiver, assets, shares);
        principalTracked += assets;
        _accrueBaseline();
    }

    /// @dev Track principal on withdrawal
    function _withdraw(
        address caller,
        address receiver,
        address owner_,
        uint256 assets,
        uint256 shares
    ) internal override whenNotPaused {
        super._withdraw(caller, receiver, owner_, assets, shares);
        if (assets > principalTracked) {
            principalTracked = 0;
        } else {
            principalTracked -= assets;
        }
        _accrueBaseline();
    }

    // ─── Performance fee harvesting ───────────────────────────────────────────

    /// @notice Harvest accumulated performance fees. Callable by authorized agents.
    ///         Calculates extra yield over baseline and mints fee shares to treasury.
    function harvest() external nonReentrant {
        if (!authorizedAgents[msg.sender]) revert NotAuthorizedAgent();
        if (block.timestamp - lastHarvestAt < MIN_HARVEST_INTERVAL) revert HarvestTooSoon();

        _accrueBaseline();

        uint256 total = totalAssets();
        if (total <= principalTracked + baselineYieldAccrued) revert NoExtraYield();

        uint256 extraYield = total - principalTracked - baselineYieldAccrued;
        uint256 feeAssets  = extraYield.mulDiv(PERFORMANCE_FEE_BPS, MAX_BPS, Math.Rounding.Floor);

        if (feeAssets == 0) revert NoExtraYield();

        // Mint fee as vault shares (dilutes existing holders proportionally)
        uint256 feeShares = previewDeposit(feeAssets);
        _mint(treasury, feeShares);

        // Absorb the fee into principalTracked so next harvest starts fresh
        principalTracked += feeAssets;
        lastHarvestAt = block.timestamp;

        emit PerformanceFeePaid(extraYield, feeShares, treasury);
    }

    // ─── Agent-callable functions ─────────────────────────────────────────────

    /// @notice CoordinatorAgent reports current cross-chain LP value each cycle
    /// @param newValue Total USD-equivalent value of positions on Ethereum + BNB (18 dec)
    function updateCrossChainAssets(uint256 newValue) external {
        if (!authorizedAgents[msg.sender]) revert NotAuthorizedAgent();
        crossChainAssetsReported = newValue;
        emit CrossChainAssetsUpdated(newValue);
    }

    /// @notice Update baseline single-chain APY used for fee calculation
    /// @param newApyBps Baseline APY in basis points (e.g. 800 = 8.00%)
    function updateBaselineApy(uint256 newApyBps) external {
        if (!authorizedAgents[msg.sender]) revert NotAuthorizedAgent();
        if (newApyBps > MAX_BPS) revert ZeroAmount(); // sanity guard
        _accrueBaseline();
        baselineApyBps = newApyBps;
        emit BaselineApyUpdated(newApyBps);
    }

    /// @notice Agent signals that a rebalance was executed (for off-chain tracking)
    function recordRebalance(uint256 amount0, uint256 amount1) external {
        if (!authorizedAgents[msg.sender]) revert NotAuthorizedAgent();
        emit RebalanceExecuted(msg.sender, amount0, amount1);
    }

    // ─── Internal helpers ─────────────────────────────────────────────────────

    /// @dev Accrue baseline yield since last snapshot into baselineYieldAccrued
    function _accrueBaseline() internal {
        uint256 elapsed = block.timestamp - lastBaselineSnapshotAt;
        if (elapsed == 0 || principalTracked == 0 || baselineApyBps == 0) return;

        // baseline yield = principal * APY * elapsed / 365 days
        uint256 accrued = principalTracked.mulDiv(
            baselineApyBps * elapsed,
            MAX_BPS * 365 days,
            Math.Rounding.Floor
        );
        baselineYieldAccrued += accrued;
        lastBaselineSnapshotAt = block.timestamp;
    }

    // ─── Admin ───────────────────────────────────────────────────────────────

    function setTreasury(address newTreasury) external onlyOwner {
        if (newTreasury == address(0)) revert ZeroAddress();
        emit TreasuryUpdated(treasury, newTreasury);
        treasury = newTreasury;
    }

    function setAgentAuthorization(address agent, bool authorized) external onlyOwner {
        if (agent == address(0)) revert ZeroAddress();
        authorizedAgents[agent] = authorized;
        emit AgentAuthorizationUpdated(agent, authorized);
    }

    function pause()   external onlyOwner { _pause(); }
    function unpause() external onlyOwner { _unpause(); }
}
